name: Deploy Project
on: [push, workflow_dispatch]
jobs:
    lint:
      runs-on: ubuntu-latest
      steps:
           - name: Get code
             uses: actions/checkout@v3    
           - name: Install Dependicies
             run: npm ci
           - name: Lint
             run: npm lint
    test:
      needs: lint
      runs-on: ubuntu-latest
      steps:
            - name: Get code
              uses: actions/checkout@v3
            - name: Install NodeJs
              uses: actions/setup-node@v3
              with:
                node-version: 18
            - name: Install dependicies
              run: npm ci
            - name: Run tests
              run: npm test   
    deploy:
      needs: test 
      runs-on: ubuntu-latest
      steps:
            - name: Get code
              uses: actions/checkout@v3
            - name: Install NodeJs
              uses: actions/setup-node@v3
              with:
                node-version: 18
            - name: Install dependicies
              run: npm ci
            - name: Build project
              run: npm build 
            - name: Deploy
              run: echo "${{ toJson(github)}}"      


